//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDBFirst
{
    using System;
    using System.Collections.Generic;
    using Interface.DAL;
    
    public partial class User : IEntity
    {
        public int Id { get; set; }
        public string DisplayName { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
